/* icons.c - Embedded Application Icons
 *
 * Contains XPM-format icon data embedded directly in the source code.
 * Provides application icon and window manager icon for PixelPrism.
 *
 * Icons:
 * - pixelprism_xpm: Main application icon (75x75, 122 colors)
 * - pixelprism_icon_xpm: Window manager icon
 *
 * XPM format allows icons to be compiled directly into the binary
 * without requiring external image files at runtime.
 */

/* XPM */
char *pixelprism_xpm[] = {
"75 75 122 2",
"  	c None",
". 	c #FF9090",
"+ 	c #FFA4A4",
"@ 	c #FFA7A7",
"# 	c #FF9292",
"$ 	c #FF7272",
"% 	c #FFD3D3",
"& 	c #FFD2D2",
"* 	c #FFCACA",
"= 	c #FFA5A5",
"- 	c #FF8383",
"; 	c #FF6E6E",
"> 	c #FF5A5A",
", 	c #FFCDCD",
"' 	c #FFBBBB",
") 	c #FF6868",
"! 	c #FF1010",
"~ 	c #FF0000",
"{ 	c #FF8585",
"] 	c #FFD1D1",
"^ 	c #FF8080",
"/ 	c #FF0707",
"( 	c #FF8282",
"_ 	c #FFC8C8",
": 	c #FF3D3D",
"< 	c #FF6B6B",
"[ 	c #FFC0C0",
"} 	c #FF2C2C",
"| 	c #FFC9C9",
"1 	c #FFCBCB",
"2 	c #FF2E2E",
"3 	c #FFA8A8",
"4 	c #FF4C4C",
"5 	c #FF6565",
"6 	c #FF8888",
"7 	c #FFAFAF",
"8 	c #FFC4C4",
"9 	c #FF1111",
"0 	c #FF6C6C",
"a 	c #FF8787",
"b 	c #FF1414",
"c 	c #FFBFBF",
"d 	c #FF9191",
"e 	c #FFB6B6",
"f 	c #FFAEAE",
"g 	c #FF0E0E",
"h 	c #FFB4B4",
"i 	c #FFB3B3",
"j 	c #FF1313",
"k 	c #FFB0B0",
"l 	c #FFB9B9",
"m 	c #FF1A1A",
"n 	c #FFBDBD",
"o 	c #FF2121",
"p 	c #FFABAB",
"q 	c #FF2323",
"r 	c #FFFFFF",
"s 	c #B0FFB0",
"t 	c #C4FFC4",
"u 	c #7FFF7F",
"v 	c #02FF02",
"w 	c #00FF00",
"x 	c #A6FFA6",
"y 	c #B9FFB9",
"z 	c #61FF61",
"A 	c #ABFFAB",
"B 	c #B6FFB6",
"C 	c #4CFF4C",
"D 	c #AFFFAF",
"E 	c #38FF38",
"F 	c #3CFF3C",
"G 	c #B4FFB4",
"H 	c #ACFFAC",
"I 	c #2AFF2A",
"J 	c #3FFF3F",
"K 	c #B5FFB5",
"L 	c #A2FFA2",
"M 	c #1CFF1C",
"N 	c #51FF51",
"O 	c #98FF98",
"P 	c #0EFF0E",
"Q 	c #5BFF5B",
"R 	c #BCFFBC",
"S 	c #93FF93",
"T 	c #0AFF0A",
"U 	c #B8FFB8",
"V 	c #8DFF8D",
"W 	c #06FF06",
"X 	c #99FF99",
"Y 	c #03FF03",
"Z 	c #8CFF8C",
"` 	c #29FF29",
" .	c #7AFF7A",
"..	c #4DFF4D",
"+.	c #54FF54",
"@.	c #0CFF0C",
"#.	c #2EFF2E",
"$.	c #0FFF0F",
"%.	c #0E0EFF",
"&.	c #5151FF",
"*.	c #0000FF",
"=.	c #5757FF",
"-.	c #7272FF",
";.	c #2F2FFF",
">.	c #9C9CFF",
",.	c #0101FF",
"'.	c #9E9EFF",
").	c #8484FF",
"!.	c #7373FF",
"~.	c #B8B8FF",
"{.	c #4242FF",
"].	c #D5D5FF",
"^.	c #5D5DFF",
"/.	c #CECEFF",
"(.	c #6C6CFF",
"_.	c #C9C9FF",
":.	c #0303FF",
"<.	c #D6D6FF",
"[.	c #8888FF",
"}.	c #A3A3FF",
"|.	c #3232FF",
"1.	c #1515FF",
"                                                                                                                                                      ",
"                                                                                                                                                      ",
"                                                                                                                                                      ",
"                                                                                                                                                      ",
"                                                                                                                                                      ",
"                                                                                                                                                      ",
"                                                                                                              . + @ # $                               ",
"                                                                                                          @ % & * = - ; >                             ",
"                                                                                                      $ , % ' ) ! ~ ~ ~ ~ ~                           ",
"                                                                                                    { % ] ^ / ~ ~ ~ ~ ~ ~ ~ ~                         ",
"                                                                                                  ( % _ : ~ ~ ~ ~ ~ ~ ~ ~ ~ ~                         ",
"                                                                                                < % [ } ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~                       ",
"                                                                                                | 1 2 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~                       ",
"                                                                                              3 ] 4 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~                         ",
"                                                                                            5 & 6 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~                         ",
"                                                                                            7 8 9 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~                         ",
"                                                                                            ] 0 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~                           ",
"                                                                                          a , b ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~                           ",
"                                                                                          c d ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~                             ",
"                                                                                        e f g ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~                               ",
"                                                                                      h i j ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~                                 ",
"                                                                                    k l m ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~                                   ",
"                                                                                  7 n o ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~                                     ",
"                                                                                p c q ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~                                         ",
"                                                                                f } ~ ~ ~ ~ ~ ~ ~ ~ ~                                                 ",
"                                                                              r r   ~ ~ ~ ~ ~ ~ ~ ~                                                   ",
"                                                                            r r r     ~ ~ ~ ~ ~ ~                                                     ",
"                                                                          r r r         ~ ~ ~ ~                                                       ",
"                                                                        r r r             ~ ~                                                         ",
"                                                                      r r r                                                                           ",
"                                                                  r r r r                                                                             ",
"                                                                r r r r                                                                               ",
"                                                              r r r                                                                                   ",
"                                                            r r r                                                                                     ",
"                                                          r r r                                                                                       ",
"                                                        r r r                                                                                         ",
"                                                      r r r                                                                                           ",
"                                                    s t u v w w w w w w                                                                               ",
"                                                  x y z w w w w w w w                                                                                 ",
"                                                A B C w w w w w w w                                                                                   ",
"                                              D s E w w w w w w w                                                                                     ",
"                                          F G H I w w w w w w w                                                                                       ",
"                                        J K L M w w w w w w w                                                                                         ",
"                                      N y O P w w w w w w w                                                                                           ",
"                                    Q R S T w w w w w w w                                                                                             ",
"                                    U V W w w w w w w w                                                                                               ",
"                                  u X Y w w w w w w w                                                                                                 ",
"                                  Z ` w w w w w w w                                                                                                   ",
"                                   .w w w w w w w                                                                                                     ",
"                                  ..w w w w w w                                                                                                       ",
"                                +.@.w w w w w                                                                                                         ",
"                                #.w w w w w                                                                                                           ",
"                                $.w                                                                                                                   ",
"                                                                                                                                                      ",
"                              %.                                                                                                                      ",
"                            &.*.                                                                                                                      ",
"                            =.*.                                                                                                                      ",
"                          -.;.*.*.                                                                                                                    ",
"                          >.,.*.*.                                                                                                                    ",
"                          '.*.*.*.                                                                                                                    ",
"                        ).!.*.*.*.*.                                                                                                                  ",
"                        ~.{.*.*.*.*.                                                                                                                  ",
"                        ].%.*.*.*.*.                                                                                                                  ",
"                      ^./.*.*.*.*.*.                                                                                                                  ",
"                      (._.*.*.*.*.*.                                                                                                                  ",
"                      -.].:.*.*.*.*.                                                                                                                  ",
"                        <.{.*.*.*.*.                                                                                                                  ",
"                        [.}.:.*.*.*.                                                                                                                  ",
"                          |.1.*.*.                                                                                                                    ",
"                                                                                                                                                      ",
"                                                                                                                                                      ",
"                                                                                                                                                      ",
"                                                                                                                                                      ",
"                                                                                                                                                      ",
"                                                                                                                                                      "};

/* XPM */
char * pixelprism_icon_xpm[] = {
"24 24 32 1",
" 	c None",
".	c #FFB4B4",
"+	c #FFB0B0",
"@	c #FF8383",
"#	c #FF3636",
"$	c #FFA3A3",
"%	c #FF1B1B",
"&	c #FF0000",
"*	c #FFA5A5",
"=	c #FF0909",
"-	c #FF5050",
";	c #FFA0A0",
">	c #FF8585",
",	c #FF0303",
"'	c #FF8989",
")	c #FF0505",
"!	c #FFFFFF",
"~	c #EEFFEE",
"{	c #89FF89",
"]	c #0EFF0E",
"^	c #00FF00",
"/	c #7EFF7E",
"(	c #04FF04",
"_	c #77FF77",
":	c #03FF03",
"<	c #59FF59",
"[	c #18FF18",
"}	c #5858FF",
"|	c #6060FF",
"1	c #0000FF",
"2	c #A7A7FF",
"3	c #6A6AFF",
"                        ",
"                        ",
"                .+@#    ",
"               +$%&&    ",
"               *=&&&    ",
"              +-&&&&    ",
"             ;>,&&&     ",
"             ')&&       ",
"            ! &&        ",
"           !            ",
"          !             ",
"         ~              ",
"        {]^             ",
"       /(^              ",
"      _:^               ",
"     <:^                ",
"     [^                 ",
"                        ",
"    }                   ",
"    |1                  ",
"   231                  ",
"    31                  ",
"                        ",
"                        "};


